Микросервис регистрации
fades-io/reg pull request #2
Opened 2022-03-02 15:17 UTC by AndrewVorotyntsev

Микросервис регистрации

Сервер прослушивает запросы по адресу `/reg` и исходя из тела запроса создает нового пользователя

2022-03-08 15:04 UTC, ShiryaevNikolay commented on internal/db/postgresql/postgresql.go
> +		return nil
Разве тут нужно nil возвращать? Нужно же как-то обработать ошибку

2022-03-08 15:04 UTC, ShiryaevNikolay commented on internal/server/controller.go
> +// TODO: implement
Этот комментарий еще актуален?

2022-03-08 15:04 UTC, ShiryaevNikolay commented on internal/server/controller.go
> +	// token, apperror := server.SignIn(user.Username, user.Password)
Эти комментарии еще нужны?

2022-03-09 09:20 UTC, AndrewVorotyntsev commented on internal/db/postgresql/postgresql.go
> +		return nil
Как я понял мы её наверх проталкиваем делегируем обработку высшим слоям

2022-03-09 09:20 UTC, AndrewVorotyntsev commented on internal/db/postgresql/postgresql.go
> +		return nil
Как раз в контроллере обработается

2022-03-09 09:21 UTC, AndrewVorotyntsev commented on internal/server/controller.go
> +// TODO: implement
Убрал

2022-03-09 09:21 UTC, AndrewVorotyntsev commented on internal/server/controller.go
> +	// token, apperror := server.SignIn(user.Username, user.Password)
Убрал

2022-03-30 14:50 UTC, igsekor requested changes
Давайте всё таки напишем отдельный код для обработки ошибок, вынесем это в отдельный блок. Помните о возможности интернациализации.

2022-03-30 14:50 UTC, igsekor commented on cmd/main.go
> +		fmt.Println("Значения из файла '.env' получены.")
Давайте выносить обработку ошибок в отдельный специальный блок. Надо бы ещё вынести все сообщения в отдельные файлы: для обработки ошибок, для логирования.

2022-03-30 14:50 UTC, igsekor commented on internal/db/postgresql/postgresql.go
> +		return nil
Обработка ошибок точно нужна.

2022-03-30 14:50 UTC, igsekor commented on internal/domain/user.go
> +			return errors.New("Требуется пароль")
Здесь ещё есть текст сообщений.

2022-04-28 08:11 UTC, igsekor approved these changes
Ну вроде рабочий вариант! 👍

2022-04-30 11:36 UTC, merged